### ISSUE TITLE
Sometimes sites fallback to base html when UltimaDark is enabled 

### ISSUE THREAD

**Issue by Vintagemotors** [ThomazPom/Moz-Ext-UltimaDark#46]
My leading theory for the moment is that cookie popups are somehow involved but I will continue trying to find a way to consistently reproduce. 

Adding: https://www.flashflashrevolution.com
Example first load 
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/3178cc28-35c7-48d4-9ce3-783d3772a53e)

The critical error from the console: Uncaught (in promise) TypeError: googletag.pubads().enableLazyLoad is not a function
    load https://stackoverflow.com/questions/3099326/what-the-difference-between-the-support-for-css-by-html4-0-and-xhtml1-0:2785 UPDATE: stackoverflow is fixed.

Happened here too: https://superuser.com/questions/1653533/how-to-switch-back-to-firefox-old-style-of-tabs UPDATE: superuser is fixed. 
error is: Uncaught (in promise) TypeError: googletag.pubads().enableLazyLoad is not a function
    load https://superuser.com/questions/1653533/how-to-switch-back-to-firefox-old-style-of-tabs:3229

**Comment by ThomazPom** [comment]
Congrats ! You just found out the oldest and most persistent bug of UltimaDark ! 
```googletag.pubads().enableLazyLoad ``` error has nothing to see with this. I'ts something due to charset used by some resource at some point. I'm also searching how to reproduce it consistently, thank you for your investigations !

**Comment by Vintagemotors** [comment]
So is there an existing issue I should merge this with?

**Comment by Vintagemotors** [comment]
New log message 

UltimaDark is loaded 
Window https://www.meta.com/experiences/4613757402035113/?utm_source=sidequest
​
"$E": function m(a)​
"$RC": function a(a, b, c)​
"$RM": Map(0)
​
"$RefreshReg$": function Y()​
"$RefreshSig$": function $RefreshSig$()​
Env: Object { isCQuick: false, jssp_header_sent: false, jssp_targeting_enabled: false, … }
​
ErrorGuard: Object { applyWithGuard: applyWithGuard(a, b, c, d), guard: guard(a, b), inGuard: inGuard()
, … }
​
ErrorSerializer: Object { aggregateError: c(a, b), toReadableMessage: d(a), toStringParams: f(a)
 }
​
ErrorUtils: Object { history: [], applyWithGuard: applyWithGuard(a, b, d, e, f, g), guard: guard(a, b, d)
, … }
​
FB_enumerate: function k(a, b)​
I_AM_CORE_COOKIE_INFRASTRUCTURE_AND_NEED_TO_ACCESS_COOKIES: function I_AM_CORE_COOKIE_INFRASTRUCTURE_AND_NEED_TO_ACCESS_COOKIES()
​
MAX_CALLS_TO_EXEC: undefined
​
ScheduleJSWork: function ScheduleJSWork(a)​
TimeSlice: Object { PropagationType: {…}, guard: guard(a, c), copyGuardForWrapper: copyGuardForWrapper(a, b)
, … }
​
UDarkOverrideRemoteContent: function UDarkOverrideRemoteContent()
​
__DEV__: 0
​
__FB_STORE: Object { "Event.listeners": {…} }
​
__SSRFailJestOnError: function C(a)​
__annotator: function e(a, b, c)​
__bodyWrapper: function g(a, b, c)​
__d: function __d(a, b, c, d, e)​
__fbNativeCancelAnimationFrame: function from cancelAnimationFramePolyfill()
​
__fbNativeClearInterval: function clearInterval()
​
__fbNativeClearTimeout: function clearTimeout()
​
__fbNativeRequestAnimationFrame: function from nativeRequestAnimationFrame()
​
__fbNativeSetInterval: function setInterval()
​
__fbNativeSetTimeout: function setTimeout()
​
__invalidateSSR: function q(a)
​
__isReactFizzContext: true
​
__logSSRQPL: function t(a)​
__m: function __m(a, b)
​
__onAfterModuleFactory: null
​
__onBeforeModuleFactory: null
​
__onSSRPayload: function x(a, b)​
__onSSRViewportGuessValidation: function u(a)​
__t: function __t(a)​
__w: function __w(a)​
_btldr: Object { YTRL02s: 1, 9CgCgq3: 1, e6Ld7No: 1, … }
​
_fbq: function fbq()​
addLoadEventListeners: function addLoadEventListeners(a)
​
as_float: true
​
babelHelpers: Object { createClass: createClass(b, c, d), inheritsLoose: inheritsLoose(a, b), wrapNativeSuper: wrapNativeSuper(a)
, … }
​
breakpages: false
​
checkDomEdit: false
​
copyVariables: function copyVariables(a)​
dataElement: <script id="envjson" type="application/json" nonce="hyYmzbJW">​
define: function S(b, c, e, g, h, i, l, m)​
emptyFunction: function emptyFunction()​
fbq: function fbq()
​
fill: false
​
getErrorSafe: function from getErrorSafe(a)​
getNodeDataSet: function getNodeDataSet(a)​
importDefault: function E(a)​
importNamespace: function F(a)​
isTagSupported: function isTagSupported(a)​
parentIsNotHeadNorBody: function parentIsNotHeadNorBody(a)​
require: function D(a)​
requireDynamic: function va(a, b)​
requireInterop: function D(a)​
requireLazy: function T(a, b, c)​
uDark: Object { disable_edit_str_cache: true, keepIdkProperties: false, chunk_stylesheets_idk_only_cors: true, … }
​
variables: Object { useTrustedTypes: true, isTrustedTypesReportOnly: true, enableDefaultTrustedTypesPolicy: true, … }
​
<default properties>
​
<prototype>: WindowPrototype { … }
4613757402035113:995:15
Uncaught DOMException: CSSStyleSheet.cssRules getter: Not allowed to access cross-origin stylesheet
    do_idk_mode https://www.meta.com/experiences/4613757402035113/?utm_source=sidequest:542
    do_idk_mode https://www.meta.com/experiences/4613757402035113/?utm_source=sidequest:540
    do_idk_mode_interval https://www.meta.com/experiences/4613757402035113/?utm_source=sidequest:494
4613757402035113:542
    do_idk_mode https://www.meta.com/experiences/4613757402035113/?utm_source=sidequest:542
    forEach self-hosted:203
    do_idk_mode https://www.meta.com/experiences/4613757402035113/?utm_source=sidequest:540
    do_idk_mode_interval https://www.meta.com/experiences/4613757402035113/?utm_source=sidequest:494

**Comment by Vintagemotors** [comment]
Proposed interim solution: some method to detect that it has happened and automatically refresh the page

**Comment by ThomazPom** [comment]
I like that idea as last resort 👍It means to have some sort of flag in resources, and detect it if missing. This is easy to do, but it would need a check for 100% of page loads to repair 1% of broken pages which is far from ideal. I'll first try to reproduce it consistently.

**Comment by ThomazPom** [comment]
> So is there an existing issue I should merge this with?
Thank you for opening this issue, it will help me by having a real reminder of the existence of this bug

**Comment by ThomazPom** [comment]
I'm not sure and have not tested it yet, but atomGit may have found a way to reproduce consistently this bug
https://github.com/ThomazPom/Moz-Ext-UltimaDark/issues/36#issuecomment-1868305306
This would be a great news

**Comment by ThomazPom** [comment]
Using UltimaDark extensively and did not get this bug since at least 15 days. Did you seen it recently ?

**Comment by CrashBandicoot0001** [comment]
I have seen it in the last week but I cannot remember on which version - it does not seem to be happening on 1.5.28, I will monitor and close next week if it does not occur again.

**Comment by Vintagemotors** [comment]
I have seen it in the last week but cannot remember which version it was (probably 1.5.26 or lower). I will close it next week as long as it does not happen again.

**Comment by Vintagemotors** [comment]
Still happening 
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/7c46801d-430b-4d1c-8d62-86a7749f717d)

**Comment by ThomazPom** [comment]
This is a very interesting case of UltimaDark causing a webpage to break. However, it's worth noting that this isn't the same bug, as this one reproduces even after using Ctrl+Shift+R.

**Comment by Vintagemotors** [comment]
Update: flashflashrevolution.com still broken on 1.5.32 (1.5.30)

**Comment by Vintagemotors** [comment]
Update: flashflashrevolution.com still broken on 1.5.33

**Comment by atomGit** [comment]
@ThomazPom said...

> atomGit may have found a way to reproduce consistently this bug.

i did, but it's not an issue anymore :) the bug affecting bitchute (loading without css) was resolved a few builds ago

as to the 3 sites listed by @Vintagemotors in the OP, they all loaded fine for me, but i'm not testing with a vanilla profile (JS is completely or partially disabled for all of them)

**Comment by Vintagemotors** [comment]
> ...they all loaded fine for me (v1.5.33), but i'm not testing with a vanilla profile (JS is completely or partially disabled for all of them)

Still broken 
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/edb91d09-e78e-4c35-acf3-0cf83d566002)


![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/6a1610a3-f5c9-43a9-91c5-fd15c341f2e4)

**Comment by ThomazPom** [comment]
The initial problem hasn't recurred based on my observation.

However, even if symptoms on these two websites looks identical, this is not the issue we were searching for:

    https://www.flashflashrevolution.com/
    https://github.com/ThomazPom/Moz-Ext-UltimaDark/issues/6#issuecomment-1884645177

Both share a common underlying cause, which is a CSS parsing issue.

**Comment by Vintagemotors** [comment]
No longer getting this issue as far as I can tell - will continue to monitor and update if it happens again otherwise closing in 2 weeks.
